### ISSUE TITLE
Missing clear() method in VectorSet!

### ISSUE THREAD

**Issue by Ali-RS** [stephengold/Heart#1]
Hi
Any reason there is no VectorSet.clear() method?

**Comment by stephengold** [comment]
Thanks for asking.

Because of how I use `VectorSet`, I've never needed to clear one. I'll make a TODO for this and let the idea incubate until Version 6.

**Comment by stephengold** [comment]
@Ali-RS Question: should the VectorSetUsingBuffer.clear() method affect the capacity of the buffer, or should it merely empty out its contents?

**Comment by Ali-RS** [comment]
Not sure, have not used VectorSetUsingBuffer, but IMO it should not affect the capacity.

**Comment by stephengold** [comment]
That sounds right.

**Comment by stephengold** [comment]
Version 5.2 is here:

    https://bintray.com/stephengold/com.github.stephengold/Heart/5.2.0for33
    https://github.com/stephengold/Heart/releases/tag/5.2.0for33

It adds `reset()` methods to both implementations of `VectorSet`, however the change to the `VectorSet` interface is still planned for v6, so I'm leaving this issue open.

**Comment by stephengold** [comment]
The interface change was introduced at SHA1 id 94f19c7a and included in the v6.0.0 release.
