### ISSUE TITLE
Shader compilation issue

### ISSUE THREAD

**Issue by rvandoosselaer** [stephengold/Heart#2]
Hi,

When enabling the `BulletDebugAppState` in Minie, the compilation of the shaders of the `Wireframe.j3md` fails when using the OpenGL3.2 core profile.
Since I'm on a Mac, this is the only profile I can use if I want OpenGL3+ support.

Stacktrace:
```
ERROR [jME3 Main] com.jme3.app.LegacyApplication (LegacyApplication.java:616) - Uncaught exception thrown in Thread[jME3 Main,5,main]
com.jme3.renderer.RendererException: compile error in: ShaderSource[name=Shaders/wireframe/wireframe.frag, defines, type=Fragment, language=GLSL110]
ERROR: 0:1: '' :  version '110' is not supported
ERROR: 0:2: '' :  #version required and missing.
```

Wireframe.j3md:
```
FragmentShader GLSL110: Shaders/wireframe/wireframe.frag
RenderState {
    Wireframe On
}
VertexShader GLSL110:   Shaders/wireframe/wireframe.vert
```
Looking at the jMonkeyEngine `Unshaded.j3md` material, I think this can be solved by adding more supported GLSL versions:

```
VertexShader GLSL310 GLSL300 GLSL100 GLSL150:   Common/MatDefs/Misc/Unshaded.vert
FragmentShader GLSL310 GLSL300 GLSL100 GLSL150: Common/MatDefs/Misc/Unshaded.frag
```

edit: I checked out Heart and did the proposed change (adding the GLSL versions) and all is working now for me. If you want I can create a PR for it.

**Comment by stephengold** [comment]
Thank you for reporting this issue. Since you've got a fix, I'd welcome a PR.

**Comment by rvandoosselaer** [comment]
I'll create the PR for it tomorrow!
